//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNDHinwil.Website.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DNDHinwil.Website.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent color.
        /// </summary>
        public static string AccentColor {
            get {
                return ResourceManager.GetString("AccentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        public static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Character.
        /// </summary>
        public static string ActiveCharacter {
            get {
                return ResourceManager.GetString("ActiveCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Effects.
        /// </summary>
        public static string ActiveEffects {
            get {
                return ResourceManager.GetString("ActiveEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduced by Armor.
        /// </summary>
        public static string AffectedByArmor {
            get {
                return ResourceManager.GetString("AffectedByArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor.
        /// </summary>
        public static string Armor {
            get {
                return ResourceManager.GetString("Armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armory.
        /// </summary>
        public static string Armory {
            get {
                return ResourceManager.GetString("Armory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character.
        /// </summary>
        public static string Character {
            get {
                return ResourceManager.GetString("Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters.
        /// </summary>
        public static string Characters {
            get {
                return ResourceManager.GetString("Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charisma.
        /// </summary>
        public static string Charisma {
            get {
                return ResourceManager.GetString("Charisma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ch.
        /// </summary>
        public static string Charisma_Short {
            get {
                return ResourceManager.GetString("Charisma_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constitution.
        /// </summary>
        public static string Constitution {
            get {
                return ResourceManager.GetString("Constitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Con.
        /// </summary>
        public static string Constitution_Short {
            get {
                return ResourceManager.GetString("Constitution_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Character.
        /// </summary>
        public static string CreateCharacter {
            get {
                return ResourceManager.GetString("CreateCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        public static string Damage {
            get {
                return ResourceManager.GetString("Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dexterity.
        /// </summary>
        public static string Dexterity {
            get {
                return ResourceManager.GetString("Dexterity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dex.
        /// </summary>
        public static string Dexterity_Short {
            get {
                return ResourceManager.GetString("Dexterity_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download your Armory.
        /// </summary>
        public static string DownloadYourArmory {
            get {
                return ResourceManager.GetString("DownloadYourArmory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download your Characters.
        /// </summary>
        public static string DownloadYourCharacters {
            get {
                return ResourceManager.GetString("DownloadYourCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download your Spell Library.
        /// </summary>
        public static string DownloadYourSpellLibrary {
            get {
                return ResourceManager.GetString("DownloadYourSpellLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect.
        /// </summary>
        public static string Effect {
            get {
                return ResourceManager.GetString("Effect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Turn.
        /// </summary>
        public static string EndTurn {
            get {
                return ResourceManager.GetString("EndTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        public static string Equipment {
            get {
                return ResourceManager.GetString("Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fireball.
        /// </summary>
        public static string Fireball {
            get {
                return ResourceManager.GetString("Fireball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heal.
        /// </summary>
        public static string Heal {
            get {
                return ResourceManager.GetString("Heal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heals.
        /// </summary>
        public static string Heals {
            get {
                return ResourceManager.GetString("Heals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health.
        /// </summary>
        public static string Health {
            get {
                return ResourceManager.GetString("Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligence.
        /// </summary>
        public static string Intelligence {
            get {
                return ResourceManager.GetString("Intelligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Int.
        /// </summary>
        public static string Intelligence_Short {
            get {
                return ResourceManager.GetString("Intelligence_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lv..
        /// </summary>
        public static string Level_Short {
            get {
                return ResourceManager.GetString("Level_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magic Power.
        /// </summary>
        public static string MagicPower {
            get {
                return ResourceManager.GetString("MagicPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP.
        /// </summary>
        public static string MagicPower_Short {
            get {
                return ResourceManager.GetString("MagicPower_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mana.
        /// </summary>
        public static string Mana {
            get {
                return ResourceManager.GetString("Mana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max HP.
        /// </summary>
        public static string MaxHP {
            get {
                return ResourceManager.GetString("MaxHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max MP.
        /// </summary>
        public static string MaxMP {
            get {
                return ResourceManager.GetString("MaxMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier.
        /// </summary>
        public static string Modifier {
            get {
                return ResourceManager.GetString("Modifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifiers.
        /// </summary>
        public static string Modifiers {
            get {
                return ResourceManager.GetString("Modifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier Table.
        /// </summary>
        public static string ModifierTable {
            get {
                return ResourceManager.GetString("ModifierTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Triggered Effect.
        /// </summary>
        public static string NewTriggeredEffect {
            get {
                return ResourceManager.GetString("NewTriggeredEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        public static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spell.
        /// </summary>
        public static string Spell {
            get {
                return ResourceManager.GetString("Spell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spellbook.
        /// </summary>
        public static string Spellbook {
            get {
                return ResourceManager.GetString("Spellbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spell Library.
        /// </summary>
        public static string SpellLibrary {
            get {
                return ResourceManager.GetString("SpellLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Turn.
        /// </summary>
        public static string StartTurn {
            get {
                return ResourceManager.GetString("StartTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats.
        /// </summary>
        public static string Stats {
            get {
                return ResourceManager.GetString("Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength.
        /// </summary>
        public static string Strength {
            get {
                return ResourceManager.GetString("Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Str.
        /// </summary>
        public static string Strength_Short {
            get {
                return ResourceManager.GetString("Strength_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Damage.
        /// </summary>
        public static string TakeDamage {
            get {
                return ResourceManager.GetString("TakeDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heal Up.
        /// </summary>
        public static string TakeHealing {
            get {
                return ResourceManager.GetString("TakeHealing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracker.
        /// </summary>
        public static string Tracker {
            get {
                return ResourceManager.GetString("Tracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triggered Effect.
        /// </summary>
        public static string TriggeredEffect {
            get {
                return ResourceManager.GetString("TriggeredEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triggers At End Of Turn.
        /// </summary>
        public static string TriggersAtEndOfTurn {
            get {
                return ResourceManager.GetString("TriggersAtEndOfTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn.
        /// </summary>
        public static string Turn {
            get {
                return ResourceManager.GetString("Turn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turns.
        /// </summary>
        public static string Turns {
            get {
                return ResourceManager.GetString("Turns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpause.
        /// </summary>
        public static string Unpause {
            get {
                return ResourceManager.GetString("Unpause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Until Healed.
        /// </summary>
        public static string UntilHealed {
            get {
                return ResourceManager.GetString("UntilHealed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Until Removed.
        /// </summary>
        public static string UntilRemoved {
            get {
                return ResourceManager.GetString("UntilRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload an Armory.
        /// </summary>
        public static string UploadArmory {
            get {
                return ResourceManager.GetString("UploadArmory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Characters.
        /// </summary>
        public static string UploadCharacters {
            get {
                return ResourceManager.GetString("UploadCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload a Spell Library.
        /// </summary>
        public static string UploadSpellLibrary {
            get {
                return ResourceManager.GetString("UploadSpellLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wisdom.
        /// </summary>
        public static string Wisdom {
            get {
                return ResourceManager.GetString("Wisdom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wis.
        /// </summary>
        public static string Wisdom_Short {
            get {
                return ResourceManager.GetString("Wisdom_Short", resourceCulture);
            }
        }
    }
}
